version: "3.9"

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    container_name: py-server-container
    volumes:
      - .:/app
    ports:
      - 8000:8000
    # environment:
    #   - DB_URL=postgresql://fastapi_traefik:fastapi_traefik@db:5432/fastapi_traefik
    depends_on:
      - redis
      - db

  redis:
    image: redislabs/redismod
    container_name: redis-container
    restart: always
    volumes:
      - redis-cached:/data
    # ports:
    #   - 6379:6379
    environment:
      - REDIS_HOST= ${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD= ${REDIS_PW}
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    # env_file:
    #   - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # MYSQL_USER: ${DB_USER}
    ports:
      - 3307:3306
    # expose:
    #   - 3307
    volumes:
      - mysql-volume:/var/lib/mysql
    # volumes:
    #   - ./backup.sql:/docker-entrypoint-initdb.d/backup.sql

volumes:
  mysql-volume:
  redis-cached:
