version: "3.9"

services:
  app:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --reload
    container_name: py-server-container
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - redis
      - db

  redis:
    image: redislabs/redismod
    container_name: redis-container
    restart: always
    volumes:
      - redis-cached:/data
    environment:
      - REDIS_HOST= ${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD= ${REDIS_PW}
  db:
    image: mysql
    container_name: mysql-container
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3307:3306
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume:
  redis-cached:
