version: "3.9"
services:
  app:
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/keys/keyfile.json
    volumes:
      # Inject your specific service account keyfile into the container at runtime.
      - ./gcp_key.json:/tmp/keys/keyfile.json:ro
