"""New revision user to add hello

Revision ID: 09340449faca
Revises: c3c63eb64e24
Create Date: 2023-04-04 12:02:48.376631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09340449faca'
down_revision = 'c3c63eb64e24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('hwllo', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'hwllo')
    # ### end Alembic commands ###
