"""change table name 

Revision ID: 18cc74283f2a
Revises: d39a96714264
Create Date: 2023-04-18 16:03:19.131768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18cc74283f2a'
down_revision = 'd39a96714264'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
