"""update product model & add size/p_item model

Revision ID: 1ac7298262e4
Revises: eefa018c4d7f
Create Date: 2023-04-18 11:25:29.042231

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1ac7298262e4'
down_revision = 'eefa018c4d7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('size',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=5), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_size_id'), 'size', ['id'], unique=False)
    op.create_table('ProductItem',
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('size_id', sa.String(length=80), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id')
    )
    op.drop_column('product', 'is_checked')
    op.drop_column('product', 'size')
    op.drop_column('product', 'availability')
    op.drop_column('product', 'qty')
    op.drop_column('product', 'sales')
    op.drop_column('product', 'stock')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('sales', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product', sa.Column('availability', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.add_column('product', sa.Column('size', mysql.VARCHAR(length=10), nullable=True))
    op.add_column('product', sa.Column('is_checked', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.drop_table('ProductItem')
    op.drop_index(op.f('ix_size_id'), table_name='size')
    op.drop_table('size')
    # ### end Alembic commands ###
