"""cart_item model's cart_id & product_id -> update to pk

Revision ID: 31d1b44580ff
Revises: dd624518ac41
Create Date: 2023-04-15 20:26:54.037276

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = '31d1b44580ff'
down_revision = 'dd624518ac41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
