"""add login type model

Revision ID: 4102135346bb
Revises: a6b128b5c82d
Create Date: 2023-04-26 16:14:45.295668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4102135346bb'
down_revision = 'a6b128b5c82d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_type',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_type_id'), 'login_type', ['id'], unique=False)
    op.create_table('user_login_type',
    sa.Column('user_id', sa.String(length=80), nullable=False),
    sa.Column('login_type_id', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['login_type_id'], ['login_type.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_login_type')
    op.drop_index(op.f('ix_login_type_id'), table_name='login_type')
    op.drop_table('login_type')
    # ### end Alembic commands ###
