"""update order_model's payment_status's default value

Revision ID: 4414a3b4f99e
Revises: 16c85aa00fb1
Create Date: 2023-04-23 13:46:19.423700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4414a3b4f99e'
down_revision = '16c85aa00fb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
