"""add size field in cart_item_mode;

Revision ID: 5134691603a5
Revises: 31d1b44580ff
Create Date: 2023-04-16 15:57:07.722485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5134691603a5'
down_revision = '31d1b44580ff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('size', sa.String(length=5), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart_item', 'size')
    # ### end Alembic commands ###
