"""add product_image_url model

Revision ID: 6ad489c8f731
Revises: 60a1bbc875f8
Create Date: 2023-04-09 22:35:04.903139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ad489c8f731'
down_revision = '60a1bbc875f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_image_url',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=350), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_image_url_id'), 'product_image_url', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_image_url_id'), table_name='product_image_url')
    op.drop_table('product_image_url')
    # ### end Alembic commands ###
