"""add Order,OrderItem models

Revision ID: 755df036bf99
Revises: b66f05aa092a
Create Date: 2023-04-10 00:03:16.704239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '755df036bf99'
down_revision = 'b66f05aa092a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_status', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('delivery_address', sa.String(length=200), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('discount_code', sa.String(length=10), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('discount_total', sa.Float(), nullable=True),
    sa.Column('shipping', sa.Float(), nullable=False),
    sa.Column('receiver_name', sa.String(length=50), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_status', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_id'), 'order', ['id'], unique=False)
    op.create_table('order_item',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_item_id'), 'order_item', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_item_id'), table_name='order_item')
    op.drop_table('order_item')
    op.drop_index(op.f('ix_order_id'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
