"""user table- email filed add nullable=True & add github_username field

Revision ID: 86241f62f1f5
Revises: 4102135346bb
Create Date: 2023-05-29 21:35:53.643326

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "86241f62f1f5"
down_revision = "4102135346bb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", type_=sa.String(length=80), nullable=True)
    op.add_column("user", sa.Column("github_username", sa.String(length=80), nullable=True))
    op.create_index(op.f("ix_user_github_username"), "user", ["github_username"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "email", nullable=False)
    op.drop_index(op.f("ix_user_github_username"), table_name="user")
    op.drop_column("user", "github_username")
    # ### end Alembic commands ###
