"""New revision user to remove hello

Revision ID: 869d25acc277
Revises: 09340449faca
Create Date: 2023-04-04 12:05:11.528641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '869d25acc277'
down_revision = '09340449faca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'hwllo')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('hwllo', mysql.VARCHAR(length=10), nullable=True))
    # ### end Alembic commands ###
