"""update order_model's paymentstatus default

Revision ID: 92e3123681c9
Revises: 8fc3e160bdab
Create Date: 2023-04-21 19:25:16.915245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92e3123681c9'
down_revision = '8fc3e160bdab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
