"""add login type model

Revision ID: a6b128b5c82d
Revises: 418c7c01960e
Create Date: 2023-04-26 16:13:04.509437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b128b5c82d'
down_revision = '418c7c01960e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
