"""add ThubnailUrl model

Revision ID: b66f05aa092a
Revises: 6ad489c8f731
Create Date: 2023-04-09 22:40:11.826989

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b66f05aa092a'
down_revision = '6ad489c8f731'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('thumbnail_url',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.String(length=350), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_thumbnail_url_id'), 'thumbnail_url', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thumbnail_url_id'), table_name='thumbnail_url')
    op.drop_table('thumbnail_url')
    # ### end Alembic commands ###
