"""New revision fir yser des

Revision ID: c3c63eb64e24
Revises: 27f5017bbe61
Create Date: 2023-04-04 12:00:45.573657

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c63eb64e24'
down_revision = '27f5017bbe61'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
