"""change order_item_model name back to singular

Revision ID: c8b64ce740a8
Revises: df6e7fa5dc6c
Create Date: 2023-04-19 12:52:23.985633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c8b64ce740a8'
down_revision = 'df6e7fa5dc6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', 'size')
    )
    op.drop_table('order_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('size', mysql.VARCHAR(length=5), nullable=False),
    sa.Column('qty', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_items_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_items_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', 'size'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('order_item')
    # ### end Alembic commands ###
