"""modified payment_url file name

Revision ID: ca9db515f6db
Revises: 4414a3b4f99e
Create Date: 2023-04-23 16:49:20.895317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca9db515f6db'
down_revision = '4414a3b4f99e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
