"""change table name 

Revision ID: d39a96714264
Revises: 1ac7298262e4
Create Date: 2023-04-18 11:27:57.267755

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd39a96714264'
down_revision = '1ac7298262e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_item',
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('size_id', sa.String(length=80), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('sales', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id')
    )
    op.drop_table('productitem')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productitem',
    sa.Column('product_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('size_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('stock', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sales', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='productitem_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['size_id'], ['size.id'], name='productitem_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'size_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('product_item')
    # ### end Alembic commands ###
