"""update cart_item model

Revision ID: dd624518ac41
Revises: 024de0eba2ea
Create Date: 2023-04-15 16:27:25.400744

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dd624518ac41'
down_revision = '024de0eba2ea'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_cart_item_id', table_name='cart_item')
    op.drop_column('cart_item', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('id', mysql.VARCHAR(length=80), nullable=False))
    op.create_index('ix_cart_item_id', 'cart_item', ['id'], unique=False)
    # ### end Alembic commands ###
