"""change order_item_model name

Revision ID: df6e7fa5dc6c
Revises: a6fc869b508f
Create Date: 2023-04-19 12:50:30.239511

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'df6e7fa5dc6c'
down_revision = 'a6fc869b508f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_items',
    sa.Column('order_id', sa.String(length=80), nullable=False),
    sa.Column('product_id', sa.String(length=80), nullable=False),
    sa.Column('size', sa.String(length=5), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('order_id', 'product_id', 'size')
    )
    op.drop_index('ix_order_item_id', table_name='order_item')
    op.drop_table('order_item')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item',
    sa.Column('id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('product_id', mysql.VARCHAR(length=80), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], name='order_item_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='order_item_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_item_id', 'order_item', ['id'], unique=False)
    op.drop_table('order_items')
    # ### end Alembic commands ###
