"""update user_coupon and coupon

Revision ID: e5afc94ca63b
Revises: 86241f62f1f5
Create Date: 2023-06-04 00:10:40.870157

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e5afc94ca63b'
down_revision = '86241f62f1f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('coupon', 'is_used')
    op.add_column('user_coupon', sa.Column('is_used', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_coupon', 'is_used')
    op.add_column('coupon', sa.Column('is_used', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
