"""change cart_item's quantity to qty

Revision ID: eefa018c4d7f
Revises: 8b3b4036c1e2
Create Date: 2023-04-17 00:23:13.088485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eefa018c4d7f'
down_revision = '8b3b4036c1e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('qty', sa.Integer(), nullable=True))
    op.drop_column('cart_item', 'qtys')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart_item', sa.Column('qtys', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('cart_item', 'qty')
    # ### end Alembic commands ###
